### ISSUE TITLE
[Request]: Integrate with Terraform for IaC

### ISSUE THREAD

**Issue by sumitag** [aws/aws-proton-public-roadmap#27] opened 2020-12-06 02:12 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

We currently use Terraform as our tool for Infrastructure as code and we would like to continue leveraging that with Proton.

**Are you currently working around this issue?**
We are currently building capabilities similar to Proton on our own

**Comment by mikesir87** [comment] 2020-12-07 15:45
Is this any different than #1?

**Comment by clareliguori** [comment] 2020-12-07 19:53
Closing as a duplicate of #1

**Closed by clareliguori** 2020-12-07 19:53 UTC
Labels: proposed
