### ISSUE TITLE
[Request]: 

### ISSUE THREAD

**Issue by augentry** [aws/aws-proton-public-roadmap#59] opened 2021-09-03 17:23 UTC
In an AWS Proton template, we define a variable using Jinja's double curly brace syntax "{{}}". Cloudformation seems to use the same syntax for [dynamic references](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html).

For example using Cloudformation to define a RDS instance with a password stored in Secrets Manager would look like:
```
MyDBInstance2:
    Type: AWS::RDS::DBInstance
    Properties:
    AllocatedStorage: 20
    DBInstanceClass: db.t2.micro
    DBName: !Ref RDSDBName
    Engine: mysql
    MasterUsername:
      Fn::Join:
        - ""
        - - "{{resolve:secretsmanager:"
          - Ref: DBCredentialsSecret
          - ":SecretString:username::}}"
    MasterUserPassword:
      Fn::Join:
        - ""
        - - "{{resolve:secretsmanager:"
          - Ref: DBCredentialsSecret
          - ":SecretString:password::}}"
    MultiAZ: False
    PubliclyAccessible: False      
    StorageType: gp2
    DBSubnetGroupName: !Ref myDBSubnetGroup
    VPCSecurityGroups:
    - !Ref RDSSecurityGroup
    BackupRetentionPeriod: 0
    DBInstanceIdentifier: 'rotation-instance'
```

Is it possible to include a dynamic reference in a Proton template? How can I tell what is going wrong with my template?

**Comment by mrpatrick** [comment] 2021-10-12 15:09
I have the same issue.  Kind of disappointing that 1. this wasn't considered when rolling out Proton and 2. there is no visibility into the resulting template (only a vague internal error).

**Comment by clareliguori** [comment] 2021-10-13 16:20
Looks like this specific issue is a dupe of https://github.com/aws/aws-proton-public-roadmap/issues/30
We'll work on getting this added to our documentation

For the issue of visibility into the generated template, I've opened this separate issue https://github.com/aws/aws-proton-public-roadmap/issues/60

**Closed as completed by clareliguori** 2021-10-13 16:20 UTC
Labels: proposed
